address=/pixiv.net/192.168.1.1
address=/www.pixiv.net/192.168.1.1
address=/oauth.secure.pixiv.net/192.168.1.1
address=/fanbox.cc/192.168.1.1
address=/www.fanbox.cc/192.168.1.1
address=/pximg.net/192.168.1.1
address=/i.pximg.net/192.168.1.1
