address=/github.com/192.168.1.1
address=/api.github.com/192.168.1.1
address=/codeload.github.com/192.168.1.1
address=/gist.github.com/192.168.1.1
address=/uploads.github.com/192.168.1.1
address=/viewscreen.githubusercontent.com/192.168.1.1
address=/raw.githubusercontent.com/192.168.1.1
address=/raw.github.com/192.168.1.1
address=/camo.githubusercontent.com/192.168.1.1
address=/cloud.githubusercontent.com/192.168.1.1
address=/avatars.githubusercontent.com/192.168.1.1
address=/avatars0.githubusercontent.com/192.168.1.1
address=/avatars1.githubusercontent.com/192.168.1.1
address=/avatars2.githubusercontent.com/192.168.1.1
address=/avatars3.githubusercontent.com/192.168.1.1
address=/user-images.githubusercontent.com/192.168.1.1
address=/private-user-images.githubusercontent.com/192.168.1.1
address=/analytics.githubassets.com/192.168.1.1
address=/desktop.githubusercontent.com/192.168.1.1
address=/github-releases.githubusercontent.com/192.168.1.1
address=/release-assets.githubusercontent.com/192.168.1.1
address=/objects.githubusercontent.com/192.168.1.1
address=/media.githubusercontent.com/192.168.1.1
address=/github.githubassets.com/192.168.1.1
address=/docs.github.com/192.168.1.1
address=/assets-cdn.github.com/192.168.1.1
address=/github.blog/192.168.1.1
