address=/store.steampowered.com/192.168.1.1
address=/checkout.steampowered.com/192.168.1.1
address=/steamcommunity.com/192.168.1.1
address=/api.steampowered.com/192.168.1.1
address=/partner.steamgames.com/192.168.1.1
address=/help.steampowered.com/192.168.1.1
address=/steam-chat.com/192.168.1.1
